server:
    port: 8085
spring:
    application:
        name: Order-Service
    data:
        mongodb:
            database: ECommerceSystem
            uri: mongodb+srv://nnirmall:nirmal123@ecommercesystem.1qknywr.mongodb.net/?retryWrites=true&w=majority&appName=ECommerceSystem
        mongodb-auto: create-drop